### ISSUE TITLE
Add a CHANGELOG

### ISSUE THREAD

**Issue by andreasabel** [blamario/incremental-parser#10]
Good for folks potentially interested in your package.

**Comment by blamario** [comment]
Done with https://github.com/blamario/incremental-parser/commit/54d164d407251c373006f8c6571fdd11d2bf25fa

**Comment by andreasabel** [comment]
Thanks!

I left some style critique at: https://github.com/blamario/incremental-parser/commit/54d164d407251c373006f8c6571fdd11d2bf25fa#r109267160
:-D
